sudo: required
services:
  - docker

before_install:
  - docker build -t nmokhrin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true -t nmokhrin/react-test npm run test -- --coverage

after_success:
  - docker build -t nmokhrin/multi-client ./client
  - docker build -t nmokhrin/multi-nginx ./nginx
  - docker build -t nmokhrin/multi-server ./server
  - docker build -t nmokhrin/multi-worker ./worker
  # Log in to the docker CLI
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  # Take those images and push them to our docker hub
  - docker push nmokhrin/multi-client
  - docker push nmokhrin/multi-nginx
  - docker push nmokhrin/multi-server
  - docker push nmokhrin/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-591464159353"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY