version: '3'
services:
  client:
    image: 'nmokhrin/multi-client'
    hostname: 'client'
  server:
    image: 'nmokhrin/multi-server'
    hostname: 'api'
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'nmokhrin/multi-worker'
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'nmokhrin/multi-nginx'
    restart: always
    ports:
      - '80:80'
